const { app, BrowserWindow, ipcMain, dialog, globalShortcut } = require('electron');
const path = require('path');

const preloadPath = app.isPackaged
    ? path.join(process.resourcesPath, 'app', 'src', 'preload.js')
    : path.join(__dirname, 'preload.js');

function createWindow() {
    const win = new BrowserWindow({
        width: 1200,
        height: 800,
        frame: true,
        autoHideMenuBar: true,
        webPreferences: {
            contextIsolation: true,
            preload: preloadPath,
        }
    });

    // point at the HTML generated by Webpack
    win.loadFile(path.join(__dirname, '..', 'dist', 'index.html'));
}

app.whenReady().then(() => {
    createWindow();
    globalShortcut.register('CommandOrControl+Alt+1', () => {
        BrowserWindow.getAllWindows()[0].webContents.send('play-sound', 'slot1');
    });

    ipcMain.handle('open-file', async () => {
        const { canceled, filePaths } = await dialog.showOpenDialog({ properties: ['openFile', 'multiSelections'] });
        return canceled ? [] : filePaths;
    });

    ipcMain.handle('getDataPath', () => {
        return app.getPath('userData');
    });

    app.on('activate', () => {
        if (BrowserWindow.getAllWindows().length === 0) createWindow();
    });
});